#include <stdlib.h> /* for NULL */
#include "opcode.h"

opcode_t op_table[256] = {
	{.disp = "NOP", .arg_type = ARG_NONE},
	{.disp = "LD   BC,%s", .arg_type = ARG_WORD},
	{.disp = "LD   (BC),A", .arg_type = ARG_NONE},
	{.disp = "INC  BC", .arg_type = ARG_NONE},
	{.disp = "INC  B", .arg_type = ARG_NONE},
	{.disp = "DEC  B", .arg_type = ARG_NONE},
	{.disp = "LD   B,%s", .arg_type = ARG_BYTE},
	{.disp = "RLCA", .arg_type = ARG_NONE},
	{.disp = "EX   AF,AF'", .arg_type = ARG_NONE},
	{.disp = "ADD  HL,BC", .arg_type = ARG_NONE},
	{.disp = "LD   A,(BC)", .arg_type = ARG_NONE},
	{.disp = "DEC  BC", .arg_type = ARG_NONE},
	{.disp = "INC  C", .arg_type = ARG_NONE},
	{.disp = "DEC  C", .arg_type = ARG_NONE},
	{.disp = "LD   C,%s", .arg_type = ARG_BYTE},
	{.disp = "RRCA", .arg_type = ARG_NONE},
	{.disp = "DJNZ dist", .arg_type = ARG_NONE},
	{.disp = "LD   DE,%s", .arg_type = ARG_WORD},
	{.disp = "LD   (DE),A", .arg_type = ARG_NONE},
	{.disp = "INC  DE", .arg_type = ARG_NONE},
	{.disp = "INC  D", .arg_type = ARG_NONE},
	{.disp = "DEC  D", .arg_type = ARG_NONE},
	{.disp = "LD   D,%s", .arg_type = ARG_BYTE},
	{.disp = "RLA", .arg_type = ARG_NONE},
	{.disp = "JR   dist", .arg_type = ARG_NONE},
	{.disp = "ADD  HL,DE", .arg_type = ARG_NONE},
	{.disp = "LD   A,(DE)", .arg_type = ARG_NONE},
	{.disp = "DEC  DE", .arg_type = ARG_NONE},
	{.disp = "INC  E", .arg_type = ARG_NONE},
	{.disp = "DEC  E", .arg_type = ARG_NONE},
	{.disp = "LD   E,%s", .arg_type = ARG_BYTE},
	{.disp = "RRA", .arg_type = ARG_NONE},
	{.disp = "JR   NZ,dist", .arg_type = ARG_NONE},
	{.disp = "LD   HL,%s", .arg_type = ARG_WORD},
	{.disp = "LD   (%s),HL", .arg_type = ARG_WORD},
	{.disp = "INC  HL", .arg_type = ARG_NONE},
	{.disp = "INC  H", .arg_type = ARG_NONE},
	{.disp = "DEC  H", .arg_type = ARG_NONE},
	{.disp = "LD   H,%s", .arg_type = ARG_BYTE},
	{.disp = "DAA", .arg_type = ARG_NONE},
	{.disp = "JR   Z,dist", .arg_type = ARG_NONE},
	{.disp = "ADD  HL,HL", .arg_type = ARG_NONE},
	{.disp = "LD   HL,(%s)", .arg_type = ARG_WORD},
	{.disp = "DEC  HL", .arg_type = ARG_NONE},
	{.disp = "INC  L", .arg_type = ARG_NONE},
	{.disp = "DEC  L", .arg_type = ARG_NONE},
	{.disp = "LD   L,%s", .arg_type = ARG_BYTE},
	{.disp = "CPL", .arg_type = ARG_NONE},
	{.disp = "JR   NC,dist", .arg_type = ARG_NONE},
	{.disp = "LD   SP,%s", .arg_type = ARG_WORD},
	{.disp = "LD   (%s),A", .arg_type = ARG_WORD},
	{.disp = "INC  SP", .arg_type = ARG_NONE},
	{.disp = "INC  (HL)", .arg_type = ARG_NONE},
	{.disp = "DEC  (HL)", .arg_type = ARG_NONE},
	{.disp = "LD   (HL),%s", .arg_type = ARG_BYTE},
	{.disp = "SCF", .arg_type = ARG_NONE},
	{.disp = "JR   C,dist", .arg_type = ARG_NONE},
	{.disp = "ADD  HL,SP", .arg_type = ARG_NONE},
	{.disp = "LD   A,(%s)", .arg_type = ARG_WORD},
	{.disp = "DEC  SP", .arg_type = ARG_NONE},
	{.disp = "INC  A", .arg_type = ARG_NONE},
	{.disp = "DEC  A", .arg_type = ARG_NONE},
	{.disp = "LD   A,%s", .arg_type = ARG_BYTE},
	{.disp = "CCF", .arg_type = ARG_NONE},
	{.disp = "LD   B,B", .arg_type = ARG_NONE},
	{.disp = "LD   B,C", .arg_type = ARG_NONE},
	{.disp = "LD   B,D", .arg_type = ARG_NONE},
	{.disp = "LD   B,E", .arg_type = ARG_NONE},
	{.disp = "LD   B,H", .arg_type = ARG_NONE},
	{.disp = "LD   B,L", .arg_type = ARG_NONE},
	{.disp = "LD   B,(HL)", .arg_type = ARG_NONE},
	{.disp = "LD   B,A", .arg_type = ARG_NONE},
	{.disp = "LD   C,B", .arg_type = ARG_NONE},
	{.disp = "LD   C,C", .arg_type = ARG_NONE},
	{.disp = "LD   C,D", .arg_type = ARG_NONE},
	{.disp = "LD   C,E", .arg_type = ARG_NONE},
	{.disp = "LD   C,H", .arg_type = ARG_NONE},
	{.disp = "LD   C,L", .arg_type = ARG_NONE},
	{.disp = "LD   C,(HL)", .arg_type = ARG_NONE},
	{.disp = "LD   C,A", .arg_type = ARG_NONE},
	{.disp = "LD   D,B", .arg_type = ARG_NONE},
	{.disp = "LD   D,C", .arg_type = ARG_NONE},
	{.disp = "LD   D,D", .arg_type = ARG_NONE},
	{.disp = "LD   D,E", .arg_type = ARG_NONE},
	{.disp = "LD   D,H", .arg_type = ARG_NONE},
	{.disp = "LD   D,L", .arg_type = ARG_NONE},
	{.disp = "LD   D,(HL)", .arg_type = ARG_NONE},
	{.disp = "LD   D,A", .arg_type = ARG_NONE},
	{.disp = "LD   E,B", .arg_type = ARG_NONE},
	{.disp = "LD   E,C", .arg_type = ARG_NONE},
	{.disp = "LD   E,D", .arg_type = ARG_NONE},
	{.disp = "LD   E,E", .arg_type = ARG_NONE},
	{.disp = "LD   E,H", .arg_type = ARG_NONE},
	{.disp = "LD   E,L", .arg_type = ARG_NONE},
	{.disp = "LD   E,(HL)", .arg_type = ARG_NONE},
	{.disp = "LD   E,A", .arg_type = ARG_NONE},
	{.disp = "LD   H,B", .arg_type = ARG_NONE},
	{.disp = "LD   H,C", .arg_type = ARG_NONE},
	{.disp = "LD   H,D", .arg_type = ARG_NONE},
	{.disp = "LD   H,E", .arg_type = ARG_NONE},
	{.disp = "LD   H,H", .arg_type = ARG_NONE},
	{.disp = "LD   H,L", .arg_type = ARG_NONE},
	{.disp = "LD   H,(HL)", .arg_type = ARG_NONE},
	{.disp = "LD   H,A", .arg_type = ARG_NONE},
	{.disp = "LD   L,B", .arg_type = ARG_NONE},
	{.disp = "LD   L,C", .arg_type = ARG_NONE},
	{.disp = "LD   L,D", .arg_type = ARG_NONE},
	{.disp = "LD   L,E", .arg_type = ARG_NONE},
	{.disp = "LD   L,H", .arg_type = ARG_NONE},
	{.disp = "LD   L,L", .arg_type = ARG_NONE},
	{.disp = "LD   L,(HL)", .arg_type = ARG_NONE},
	{.disp = "LD   L,A", .arg_type = ARG_NONE},
	{.disp = "LD   (HL),B", .arg_type = ARG_NONE},
	{.disp = "LD   (HL),C", .arg_type = ARG_NONE},
	{.disp = "LD   (HL),D", .arg_type = ARG_NONE},
	{.disp = "LD   (HL),E", .arg_type = ARG_NONE},
	{.disp = "LD   (HL),H", .arg_type = ARG_NONE},
	{.disp = "LD   (HL),L", .arg_type = ARG_NONE},
	{.disp = "HALT", .arg_type = ARG_NONE},
	{.disp = "LD   (HL),A", .arg_type = ARG_NONE},
	{.disp = "LD   A,B", .arg_type = ARG_NONE},
	{.disp = "LD   A,C", .arg_type = ARG_NONE},
	{.disp = "LD   A,D", .arg_type = ARG_NONE},
	{.disp = "LD   A,E", .arg_type = ARG_NONE},
	{.disp = "LD   A,H", .arg_type = ARG_NONE},
	{.disp = "LD   A,L", .arg_type = ARG_NONE},
	{.disp = "LD   A,(HL)", .arg_type = ARG_NONE},
	{.disp = "LD   A,A", .arg_type = ARG_NONE},
	{.disp = "ADD  A,B", .arg_type = ARG_NONE},
	{.disp = "ADD  A,C", .arg_type = ARG_NONE},
	{.disp = "ADD  A,D", .arg_type = ARG_NONE},
	{.disp = "ADD  A,E", .arg_type = ARG_NONE},
	{.disp = "ADD  A,H", .arg_type = ARG_NONE},
	{.disp = "ADD  A,L", .arg_type = ARG_NONE},
	{.disp = "ADD  A,(HL)", .arg_type = ARG_NONE},
	{.disp = "ADD  A,A", .arg_type = ARG_NONE},
	{.disp = "ADC  A,B", .arg_type = ARG_NONE},
	{.disp = "ADC  A,C", .arg_type = ARG_NONE},
	{.disp = "ADC  A,D", .arg_type = ARG_NONE},
	{.disp = "ADC  A,E", .arg_type = ARG_NONE},
	{.disp = "ADC  A,H", .arg_type = ARG_NONE},
	{.disp = "ADC  A,L", .arg_type = ARG_NONE},
	{.disp = "ADC  A,(HL)", .arg_type = ARG_NONE},
	{.disp = "ADC  A,A", .arg_type = ARG_NONE},
	{.disp = "SUB  A,B", .arg_type = ARG_NONE},
	{.disp = "SUB  A,C", .arg_type = ARG_NONE},
	{.disp = "SUB  A,D", .arg_type = ARG_NONE},
	{.disp = "SUB  A,E", .arg_type = ARG_NONE},
	{.disp = "SUB  A,H", .arg_type = ARG_NONE},
	{.disp = "SUB  A,L", .arg_type = ARG_NONE},
	{.disp = "SUB  A,(HL)", .arg_type = ARG_NONE},
	{.disp = "SUB  A,A", .arg_type = ARG_NONE},
	{.disp = "SBC  A,B", .arg_type = ARG_NONE},
	{.disp = "SBC  A,C", .arg_type = ARG_NONE},
	{.disp = "SBC  A,D", .arg_type = ARG_NONE},
	{.disp = "SBC  A,E", .arg_type = ARG_NONE},
	{.disp = "SBC  A,H", .arg_type = ARG_NONE},
	{.disp = "SBC  A,L", .arg_type = ARG_NONE},
	{.disp = "SBC  A,(HL)", .arg_type = ARG_NONE},
	{.disp = "SBC  A,A", .arg_type = ARG_NONE},
	{.disp = "AND  B", .arg_type = ARG_NONE},
	{.disp = "AND  C", .arg_type = ARG_NONE},
	{.disp = "AND  D", .arg_type = ARG_NONE},
	{.disp = "AND  E", .arg_type = ARG_NONE},
	{.disp = "AND  H", .arg_type = ARG_NONE},
	{.disp = "AND  L", .arg_type = ARG_NONE},
	{.disp = "AND  (HL)", .arg_type = ARG_NONE},
	{.disp = "AND  A", .arg_type = ARG_NONE},
	{.disp = "XOR  B", .arg_type = ARG_NONE},
	{.disp = "XOR  C", .arg_type = ARG_NONE},
	{.disp = "XOR  D", .arg_type = ARG_NONE},
	{.disp = "XOR  E", .arg_type = ARG_NONE},
	{.disp = "XOR  H", .arg_type = ARG_NONE},
	{.disp = "XOR  L", .arg_type = ARG_NONE},
	{.disp = "XOR  (HL)", .arg_type = ARG_NONE},
	{.disp = "XOR  A", .arg_type = ARG_NONE},
	{.disp = "OR   B", .arg_type = ARG_NONE},
	{.disp = "OR   C", .arg_type = ARG_NONE},
	{.disp = "OR   D", .arg_type = ARG_NONE},
	{.disp = "OR   E", .arg_type = ARG_NONE},
	{.disp = "OR   H", .arg_type = ARG_NONE},
	{.disp = "OR   L", .arg_type = ARG_NONE},
	{.disp = "OR   (HL)", .arg_type = ARG_NONE},
	{.disp = "OR   A", .arg_type = ARG_NONE},
	{.disp = "CP   B", .arg_type = ARG_NONE},
	{.disp = "CP   C", .arg_type = ARG_NONE},
	{.disp = "CP   D", .arg_type = ARG_NONE},
	{.disp = "CP   E", .arg_type = ARG_NONE},
	{.disp = "CP   H", .arg_type = ARG_NONE},
	{.disp = "CP   L", .arg_type = ARG_NONE},
	{.disp = "CP   (HL)", .arg_type = ARG_NONE},
	{.disp = "CP   A", .arg_type = ARG_NONE},
	{.disp = "RET  NZ", .arg_type = ARG_NONE},
	{.disp = "POP  BC", .arg_type = ARG_NONE},
	{.disp = "JP   NZ,%s", .arg_type = ARG_WORD},
	{.disp = "JP   %s", .arg_type = ARG_WORD},
	{.disp = "CALL NZ,%s", .arg_type = ARG_WORD},
	{.disp = "PUSH BC", .arg_type = ARG_NONE},
	{.disp = "ADD  A,%s", .arg_type = ARG_BYTE},
	{.disp = "RST  00h", .arg_type = ARG_NONE},
	{.disp = "RET  Z", .arg_type = ARG_NONE},
	{.disp = "RET", .arg_type = ARG_NONE},
	{.disp = "JP   Z,%s", .arg_type = ARG_WORD},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "CALL Z,%s", .arg_type = ARG_WORD},
	{.disp = "CALL %s", .arg_type = ARG_WORD},
	{.disp = "ADC  A,%s", .arg_type = ARG_BYTE},
	{.disp = "RST  08h", .arg_type = ARG_NONE},
	{.disp = "RET  NC", .arg_type = ARG_NONE},
	{.disp = "POP  DE", .arg_type = ARG_NONE},
	{.disp = "JP   NC,%s", .arg_type = ARG_WORD},
	{.disp = "OUT  (%s),A", .arg_type = ARG_BYTE},
	{.disp = "CALL NC,%s", .arg_type = ARG_WORD},
	{.disp = "PUSH DE", .arg_type = ARG_NONE},
	{.disp = "SUB  A,%s", .arg_type = ARG_BYTE},
	{.disp = "RST  10h", .arg_type = ARG_NONE},
	{.disp = "RET  C", .arg_type = ARG_NONE},
	{.disp = "EXX", .arg_type = ARG_NONE},
	{.disp = "JP   C,%s", .arg_type = ARG_WORD},
	{.disp = "IN   A,(%s)", .arg_type = ARG_BYTE},
	{.disp = "CALL C,%s", .arg_type = ARG_WORD},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SBC  A,%s", .arg_type = ARG_BYTE},
	{.disp = "RST  18h", .arg_type = ARG_NONE},
	{.disp = "RET  PO", .arg_type = ARG_NONE},
	{.disp = "POP  HL", .arg_type = ARG_NONE},
	{.disp = "JP   PO,%s", .arg_type = ARG_WORD},
	{.disp = "EX   (SP),HL", .arg_type = ARG_NONE},
	{.disp = "CALL PO,%s", .arg_type = ARG_WORD},
	{.disp = "PUSH HL", .arg_type = ARG_NONE},
	{.disp = "AND  %s", .arg_type = ARG_BYTE},
	{.disp = "RST  20h", .arg_type = ARG_NONE},
	{.disp = "RET  PE", .arg_type = ARG_NONE},
	{.disp = "JP   (HL)", .arg_type = ARG_NONE},
	{.disp = "JP   PE,%s", .arg_type = ARG_WORD},
	{.disp = "EX   DE,HL", .arg_type = ARG_NONE},
	{.disp = "CALL PE,%s", .arg_type = ARG_WORD},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "XOR  %s", .arg_type = ARG_BYTE},
	{.disp = "RST  28h", .arg_type = ARG_NONE},
	{.disp = "RET  P", .arg_type = ARG_NONE},
	{.disp = "POP  AF", .arg_type = ARG_NONE},
	{.disp = "JP   P,%s", .arg_type = ARG_WORD},
	{.disp = "DI", .arg_type = ARG_NONE},
	{.disp = "CALL P,%s", .arg_type = ARG_WORD},
	{.disp = "PUSH AF", .arg_type = ARG_NONE},
	{.disp = "OR   %s", .arg_type = ARG_BYTE},
	{.disp = "RST  30h", .arg_type = ARG_NONE},
	{.disp = "RET  M", .arg_type = ARG_NONE},
	{.disp = "LD   SP,HL", .arg_type = ARG_NONE},
	{.disp = "JP   M,%s", .arg_type = ARG_WORD},
	{.disp = "EI", .arg_type = ARG_NONE},
	{.disp = "CALL M,%s", .arg_type = ARG_WORD},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "CP   %s", .arg_type = ARG_BYTE},
	{.disp = "RST  38h", .arg_type = ARG_NONE},
};

opcode_t cb_table[256] = {
	{.disp = "RLC  B", .arg_type = ARG_NONE},
	{.disp = "RLC  C", .arg_type = ARG_NONE},
	{.disp = "RLC  D", .arg_type = ARG_NONE},
	{.disp = "RLC  E", .arg_type = ARG_NONE},
	{.disp = "RLC  H", .arg_type = ARG_NONE},
	{.disp = "RLC  L", .arg_type = ARG_NONE},
	{.disp = "RLC  (HL)", .arg_type = ARG_NONE},
	{.disp = "RLC  A", .arg_type = ARG_NONE},
	{.disp = "RRC  B", .arg_type = ARG_NONE},
	{.disp = "RRC  C", .arg_type = ARG_NONE},
	{.disp = "RRC  D", .arg_type = ARG_NONE},
	{.disp = "RRC  E", .arg_type = ARG_NONE},
	{.disp = "RRC  H", .arg_type = ARG_NONE},
	{.disp = "RRC  L", .arg_type = ARG_NONE},
	{.disp = "RRC  (HL)", .arg_type = ARG_NONE},
	{.disp = "RRC  A", .arg_type = ARG_NONE},
	{.disp = "RL   B", .arg_type = ARG_NONE},
	{.disp = "RL   C", .arg_type = ARG_NONE},
	{.disp = "RL   D", .arg_type = ARG_NONE},
	{.disp = "RL   E", .arg_type = ARG_NONE},
	{.disp = "RL   H", .arg_type = ARG_NONE},
	{.disp = "RL   L", .arg_type = ARG_NONE},
	{.disp = "RL   (HL)", .arg_type = ARG_NONE},
	{.disp = "RL   A", .arg_type = ARG_NONE},
	{.disp = "RR   B", .arg_type = ARG_NONE},
	{.disp = "RR   C", .arg_type = ARG_NONE},
	{.disp = "RR   D", .arg_type = ARG_NONE},
	{.disp = "RR   E", .arg_type = ARG_NONE},
	{.disp = "RR   H", .arg_type = ARG_NONE},
	{.disp = "RR   L", .arg_type = ARG_NONE},
	{.disp = "RR   (HL)", .arg_type = ARG_NONE},
	{.disp = "RR   A", .arg_type = ARG_NONE},
	{.disp = "SLA  B", .arg_type = ARG_NONE},
	{.disp = "SLA  C", .arg_type = ARG_NONE},
	{.disp = "SLA  D", .arg_type = ARG_NONE},
	{.disp = "SLA  E", .arg_type = ARG_NONE},
	{.disp = "SLA  H", .arg_type = ARG_NONE},
	{.disp = "SLA  L", .arg_type = ARG_NONE},
	{.disp = "SLA  (HL)", .arg_type = ARG_NONE},
	{.disp = "SLA  A", .arg_type = ARG_NONE},
	{.disp = "SRA  B", .arg_type = ARG_NONE},
	{.disp = "SRA  C", .arg_type = ARG_NONE},
	{.disp = "SRA  D", .arg_type = ARG_NONE},
	{.disp = "SRA  E", .arg_type = ARG_NONE},
	{.disp = "SRA  H", .arg_type = ARG_NONE},
	{.disp = "SRA  L", .arg_type = ARG_NONE},
	{.disp = "SRA  (HL)", .arg_type = ARG_NONE},
	{.disp = "SRA  A", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SRL  B", .arg_type = ARG_NONE},
	{.disp = "SRL  C", .arg_type = ARG_NONE},
	{.disp = "SRL  D", .arg_type = ARG_NONE},
	{.disp = "SRL  E", .arg_type = ARG_NONE},
	{.disp = "SRL  H", .arg_type = ARG_NONE},
	{.disp = "SRL  L", .arg_type = ARG_NONE},
	{.disp = "SRL  (HL)", .arg_type = ARG_NONE},
	{.disp = "SRL  A", .arg_type = ARG_NONE},
	{.disp = "BIT  0,B", .arg_type = ARG_NONE},
	{.disp = "BIT  0,C", .arg_type = ARG_NONE},
	{.disp = "BIT  0,D", .arg_type = ARG_NONE},
	{.disp = "BIT  0,E", .arg_type = ARG_NONE},
	{.disp = "BIT  0,H", .arg_type = ARG_NONE},
	{.disp = "BIT  0,L", .arg_type = ARG_NONE},
	{.disp = "BIT  0,(HL)", .arg_type = ARG_NONE},
	{.disp = "BIT  0,A", .arg_type = ARG_NONE},
	{.disp = "BIT  1,B", .arg_type = ARG_NONE},
	{.disp = "BIT  1,C", .arg_type = ARG_NONE},
	{.disp = "BIT  1,D", .arg_type = ARG_NONE},
	{.disp = "BIT  1,E", .arg_type = ARG_NONE},
	{.disp = "BIT  1,H", .arg_type = ARG_NONE},
	{.disp = "BIT  1,L", .arg_type = ARG_NONE},
	{.disp = "BIT  1,(HL)", .arg_type = ARG_NONE},
	{.disp = "BIT  1,A", .arg_type = ARG_NONE},
	{.disp = "BIT  2,B", .arg_type = ARG_NONE},
	{.disp = "BIT  2,C", .arg_type = ARG_NONE},
	{.disp = "BIT  2,D", .arg_type = ARG_NONE},
	{.disp = "BIT  2,E", .arg_type = ARG_NONE},
	{.disp = "BIT  2,H", .arg_type = ARG_NONE},
	{.disp = "BIT  2,L", .arg_type = ARG_NONE},
	{.disp = "BIT  2,(HL)", .arg_type = ARG_NONE},
	{.disp = "BIT  2,A", .arg_type = ARG_NONE},
	{.disp = "BIT  3,B", .arg_type = ARG_NONE},
	{.disp = "BIT  3,C", .arg_type = ARG_NONE},
	{.disp = "BIT  3,D", .arg_type = ARG_NONE},
	{.disp = "BIT  3,E", .arg_type = ARG_NONE},
	{.disp = "BIT  3,H", .arg_type = ARG_NONE},
	{.disp = "BIT  3,L", .arg_type = ARG_NONE},
	{.disp = "BIT  3,(HL)", .arg_type = ARG_NONE},
	{.disp = "BIT  3,A", .arg_type = ARG_NONE},
	{.disp = "BIT  4,B", .arg_type = ARG_NONE},
	{.disp = "BIT  4,C", .arg_type = ARG_NONE},
	{.disp = "BIT  4,D", .arg_type = ARG_NONE},
	{.disp = "BIT  4,E", .arg_type = ARG_NONE},
	{.disp = "BIT  4,H", .arg_type = ARG_NONE},
	{.disp = "BIT  4,L", .arg_type = ARG_NONE},
	{.disp = "BIT  4,(HL)", .arg_type = ARG_NONE},
	{.disp = "BIT  4,A", .arg_type = ARG_NONE},
	{.disp = "BIT  5,B", .arg_type = ARG_NONE},
	{.disp = "BIT  5,C", .arg_type = ARG_NONE},
	{.disp = "BIT  5,D", .arg_type = ARG_NONE},
	{.disp = "BIT  5,E", .arg_type = ARG_NONE},
	{.disp = "BIT  5,H", .arg_type = ARG_NONE},
	{.disp = "BIT  5,L", .arg_type = ARG_NONE},
	{.disp = "BIT  5,(HL)", .arg_type = ARG_NONE},
	{.disp = "BIT  5,A", .arg_type = ARG_NONE},
	{.disp = "BIT  6,B", .arg_type = ARG_NONE},
	{.disp = "BIT  6,C", .arg_type = ARG_NONE},
	{.disp = "BIT  6,D", .arg_type = ARG_NONE},
	{.disp = "BIT  6,E", .arg_type = ARG_NONE},
	{.disp = "BIT  6,H", .arg_type = ARG_NONE},
	{.disp = "BIT  6,L", .arg_type = ARG_NONE},
	{.disp = "BIT  6,(HL)", .arg_type = ARG_NONE},
	{.disp = "BIT  6,A", .arg_type = ARG_NONE},
	{.disp = "BIT  7,B", .arg_type = ARG_NONE},
	{.disp = "BIT  7,C", .arg_type = ARG_NONE},
	{.disp = "BIT  7,D", .arg_type = ARG_NONE},
	{.disp = "BIT  7,E", .arg_type = ARG_NONE},
	{.disp = "BIT  7,H", .arg_type = ARG_NONE},
	{.disp = "BIT  7,L", .arg_type = ARG_NONE},
	{.disp = "BIT  7,(HL)", .arg_type = ARG_NONE},
	{.disp = "BIT  7,A", .arg_type = ARG_NONE},
	{.disp = "RES  0,B", .arg_type = ARG_NONE},
	{.disp = "RES  0,C", .arg_type = ARG_NONE},
	{.disp = "RES  0,D", .arg_type = ARG_NONE},
	{.disp = "RES  0,E", .arg_type = ARG_NONE},
	{.disp = "RES  0,H", .arg_type = ARG_NONE},
	{.disp = "RES  0,L", .arg_type = ARG_NONE},
	{.disp = "RES  0,(HL)", .arg_type = ARG_NONE},
	{.disp = "RES  0,A", .arg_type = ARG_NONE},
	{.disp = "RES  1,B", .arg_type = ARG_NONE},
	{.disp = "RES  1,C", .arg_type = ARG_NONE},
	{.disp = "RES  1,D", .arg_type = ARG_NONE},
	{.disp = "RES  1,E", .arg_type = ARG_NONE},
	{.disp = "RES  1,H", .arg_type = ARG_NONE},
	{.disp = "RES  1,L", .arg_type = ARG_NONE},
	{.disp = "RES  1,(HL)", .arg_type = ARG_NONE},
	{.disp = "RES  1,A", .arg_type = ARG_NONE},
	{.disp = "RES  2,B", .arg_type = ARG_NONE},
	{.disp = "RES  2,C", .arg_type = ARG_NONE},
	{.disp = "RES  2,D", .arg_type = ARG_NONE},
	{.disp = "RES  2,E", .arg_type = ARG_NONE},
	{.disp = "RES  2,H", .arg_type = ARG_NONE},
	{.disp = "RES  2,L", .arg_type = ARG_NONE},
	{.disp = "RES  2,(HL)", .arg_type = ARG_NONE},
	{.disp = "RES  2,A", .arg_type = ARG_NONE},
	{.disp = "RES  3,B", .arg_type = ARG_NONE},
	{.disp = "RES  3,C", .arg_type = ARG_NONE},
	{.disp = "RES  3,D", .arg_type = ARG_NONE},
	{.disp = "RES  3,E", .arg_type = ARG_NONE},
	{.disp = "RES  3,H", .arg_type = ARG_NONE},
	{.disp = "RES  3,L", .arg_type = ARG_NONE},
	{.disp = "RES  3,(HL)", .arg_type = ARG_NONE},
	{.disp = "RES  3,A", .arg_type = ARG_NONE},
	{.disp = "RES  4,B", .arg_type = ARG_NONE},
	{.disp = "RES  4,C", .arg_type = ARG_NONE},
	{.disp = "RES  4,D", .arg_type = ARG_NONE},
	{.disp = "RES  4,E", .arg_type = ARG_NONE},
	{.disp = "RES  4,H", .arg_type = ARG_NONE},
	{.disp = "RES  4,L", .arg_type = ARG_NONE},
	{.disp = "RES  4,(HL)", .arg_type = ARG_NONE},
	{.disp = "RES  4,A", .arg_type = ARG_NONE},
	{.disp = "RES  5,B", .arg_type = ARG_NONE},
	{.disp = "RES  5,C", .arg_type = ARG_NONE},
	{.disp = "RES  5,D", .arg_type = ARG_NONE},
	{.disp = "RES  5,E", .arg_type = ARG_NONE},
	{.disp = "RES  5,H", .arg_type = ARG_NONE},
	{.disp = "RES  5,L", .arg_type = ARG_NONE},
	{.disp = "RES  5,(HL)", .arg_type = ARG_NONE},
	{.disp = "RES  5,A", .arg_type = ARG_NONE},
	{.disp = "RES  6,B", .arg_type = ARG_NONE},
	{.disp = "RES  6,C", .arg_type = ARG_NONE},
	{.disp = "RES  6,D", .arg_type = ARG_NONE},
	{.disp = "RES  6,E", .arg_type = ARG_NONE},
	{.disp = "RES  6,H", .arg_type = ARG_NONE},
	{.disp = "RES  6,L", .arg_type = ARG_NONE},
	{.disp = "RES  6,(HL)", .arg_type = ARG_NONE},
	{.disp = "RES  6,A", .arg_type = ARG_NONE},
	{.disp = "RES  7,B", .arg_type = ARG_NONE},
	{.disp = "RES  7,C", .arg_type = ARG_NONE},
	{.disp = "RES  7,D", .arg_type = ARG_NONE},
	{.disp = "RES  7,E", .arg_type = ARG_NONE},
	{.disp = "RES  7,H", .arg_type = ARG_NONE},
	{.disp = "RES  7,L", .arg_type = ARG_NONE},
	{.disp = "RES  7,(HL)", .arg_type = ARG_NONE},
	{.disp = "RES  7,A", .arg_type = ARG_NONE},
	{.disp = "SET  0,B", .arg_type = ARG_NONE},
	{.disp = "SET  0,C", .arg_type = ARG_NONE},
	{.disp = "SET  0,D", .arg_type = ARG_NONE},
	{.disp = "SET  0,E", .arg_type = ARG_NONE},
	{.disp = "SET  0,H", .arg_type = ARG_NONE},
	{.disp = "SET  0,L", .arg_type = ARG_NONE},
	{.disp = "SET  0,(HL)", .arg_type = ARG_NONE},
	{.disp = "SET  0,A", .arg_type = ARG_NONE},
	{.disp = "SET  1,B", .arg_type = ARG_NONE},
	{.disp = "SET  1,C", .arg_type = ARG_NONE},
	{.disp = "SET  1,D", .arg_type = ARG_NONE},
	{.disp = "SET  1,E", .arg_type = ARG_NONE},
	{.disp = "SET  1,H", .arg_type = ARG_NONE},
	{.disp = "SET  1,L", .arg_type = ARG_NONE},
	{.disp = "SET  1,(HL)", .arg_type = ARG_NONE},
	{.disp = "SET  1,A", .arg_type = ARG_NONE},
	{.disp = "SET  2,B", .arg_type = ARG_NONE},
	{.disp = "SET  2,C", .arg_type = ARG_NONE},
	{.disp = "SET  2,D", .arg_type = ARG_NONE},
	{.disp = "SET  2,E", .arg_type = ARG_NONE},
	{.disp = "SET  2,H", .arg_type = ARG_NONE},
	{.disp = "SET  2,L", .arg_type = ARG_NONE},
	{.disp = "SET  2,(HL)", .arg_type = ARG_NONE},
	{.disp = "SET  2,A", .arg_type = ARG_NONE},
	{.disp = "SET  3,B", .arg_type = ARG_NONE},
	{.disp = "SET  3,C", .arg_type = ARG_NONE},
	{.disp = "SET  3,D", .arg_type = ARG_NONE},
	{.disp = "SET  3,E", .arg_type = ARG_NONE},
	{.disp = "SET  3,H", .arg_type = ARG_NONE},
	{.disp = "SET  3,L", .arg_type = ARG_NONE},
	{.disp = "SET  3,(HL)", .arg_type = ARG_NONE},
	{.disp = "SET  3,A", .arg_type = ARG_NONE},
	{.disp = "SET  4,B", .arg_type = ARG_NONE},
	{.disp = "SET  4,C", .arg_type = ARG_NONE},
	{.disp = "SET  4,D", .arg_type = ARG_NONE},
	{.disp = "SET  4,E", .arg_type = ARG_NONE},
	{.disp = "SET  4,H", .arg_type = ARG_NONE},
	{.disp = "SET  4,L", .arg_type = ARG_NONE},
	{.disp = "SET  4,(HL)", .arg_type = ARG_NONE},
	{.disp = "SET  4,A", .arg_type = ARG_NONE},
	{.disp = "SET  5,B", .arg_type = ARG_NONE},
	{.disp = "SET  5,C", .arg_type = ARG_NONE},
	{.disp = "SET  5,D", .arg_type = ARG_NONE},
	{.disp = "SET  5,E", .arg_type = ARG_NONE},
	{.disp = "SET  5,H", .arg_type = ARG_NONE},
	{.disp = "SET  5,L", .arg_type = ARG_NONE},
	{.disp = "SET  5,(HL)", .arg_type = ARG_NONE},
	{.disp = "SET  5,A", .arg_type = ARG_NONE},
	{.disp = "SET  6,B", .arg_type = ARG_NONE},
	{.disp = "SET  6,C", .arg_type = ARG_NONE},
	{.disp = "SET  6,D", .arg_type = ARG_NONE},
	{.disp = "SET  6,E", .arg_type = ARG_NONE},
	{.disp = "SET  6,H", .arg_type = ARG_NONE},
	{.disp = "SET  6,L", .arg_type = ARG_NONE},
	{.disp = "SET  6,(HL)", .arg_type = ARG_NONE},
	{.disp = "SET  6,A", .arg_type = ARG_NONE},
	{.disp = "SET  7,B", .arg_type = ARG_NONE},
	{.disp = "SET  7,C", .arg_type = ARG_NONE},
	{.disp = "SET  7,D", .arg_type = ARG_NONE},
	{.disp = "SET  7,E", .arg_type = ARG_NONE},
	{.disp = "SET  7,H", .arg_type = ARG_NONE},
	{.disp = "SET  7,L", .arg_type = ARG_NONE},
	{.disp = "SET  7,(HL)", .arg_type = ARG_NONE},
	{.disp = "SET  7,A", .arg_type = ARG_NONE},
};

opcode_t ed_table[256] = {
	{.disp = "IN0  B,(%s)", .arg_type = ARG_BYTE},
	{.disp = "OUT0 (%s),B", .arg_type = ARG_BYTE},
	{.disp = "LEA  BC,IX+%s", .arg_type = ARG_BYTE},
	{.disp = "LEA  BC,IY+%s", .arg_type = ARG_BYTE},
	{.disp = "TST  A,B", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   BC,(HL)", .arg_type = ARG_NONE},
	{.disp = "IN0  C,(%s)", .arg_type = ARG_BYTE},
	{.disp = "OUT0 (%s),C", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "TST  A,C", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (HL),BC", .arg_type = ARG_NONE},
	{.disp = "IN0  D,(%s)", .arg_type = ARG_BYTE},
	{.disp = "OUT0 (%s),D", .arg_type = ARG_BYTE},
	{.disp = "LEA  DE,IX+%s", .arg_type = ARG_BYTE},
	{.disp = "LEA  DE,IY+%s", .arg_type = ARG_BYTE},
	{.disp = "TST  A,D", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   DE,(HL)", .arg_type = ARG_NONE},
	{.disp = "IN0  E,(%s)", .arg_type = ARG_BYTE},
	{.disp = "OUT0 (%s),E", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "TST  A,E", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (HL),DE", .arg_type = ARG_NONE},
	{.disp = "IN0  H,(%s)", .arg_type = ARG_BYTE},
	{.disp = "OUT0 (%s),H", .arg_type = ARG_BYTE},
	{.disp = "LEA  HL,IX+%s", .arg_type = ARG_BYTE},
	{.disp = "LEA  HL,IY+%s", .arg_type = ARG_BYTE},
	{.disp = "TST  A,H", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   HL,(HL)", .arg_type = ARG_NONE},
	{.disp = "IN0  L,(%s)", .arg_type = ARG_BYTE},
	{.disp = "OUT0 (%s),L", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "TST  A,L", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (HL),HL", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LEA  IX,IX+%s", .arg_type = ARG_BYTE},
	{.disp = "LEA  IY,IY+%s", .arg_type = ARG_BYTE},
	{.disp = "TST  A,(HL)", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   IY,(HL)", .arg_type = ARG_NONE},
	{.disp = "LD   IX,(HL)", .arg_type = ARG_NONE},
	{.disp = "IN0  A,(%s)", .arg_type = ARG_BYTE},
	{.disp = "OUT0 (%s),A", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "TST  A,A", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD  (HL),IY", .arg_type = ARG_NONE},
	{.disp = "LD  (HL),IX", .arg_type = ARG_NONE},
	{.disp = "IN   B,(BC)", .arg_type = ARG_NONE},
	{.disp = "OUT  (BC),B", .arg_type = ARG_NONE},
	{.disp = "SBC  HL,BC", .arg_type = ARG_NONE},
	{.disp = "LD   (%s),BC", .arg_type = ARG_WORD},
	{.disp = "NEG", .arg_type = ARG_NONE},
	{.disp = "RETN", .arg_type = ARG_NONE},
	{.disp = "IM   0", .arg_type = ARG_NONE},
	{.disp = "LD   I,A", .arg_type = ARG_NONE},
	{.disp = "IN   C,(BC)", .arg_type = ARG_NONE},
	{.disp = "OUT  (BC),C", .arg_type = ARG_NONE},
	{.disp = "ADC  HL,BC", .arg_type = ARG_NONE},
	{.disp = "LD   BC,(%s)", .arg_type = ARG_WORD},
	{.disp = "MULT BC", .arg_type = ARG_NONE},
	{.disp = "RETI", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   R,A", .arg_type = ARG_NONE},
	{.disp = "IN   D,(BC)", .arg_type = ARG_NONE},
	{.disp = "OUT  (BC),D", .arg_type = ARG_NONE},
	{.disp = "SBC  HL,DE", .arg_type = ARG_NONE},
	{.disp = "LD   (%s),DE", .arg_type = ARG_WORD},
	{.disp = "LEA  IX,IY+%s", .arg_type = ARG_BYTE},
	{.disp = "LEA  IY,IX+%s", .arg_type = ARG_BYTE},
	{.disp = "IM   1", .arg_type = ARG_NONE},
	{.disp = "LD   A,I", .arg_type = ARG_NONE},
	{.disp = "IN   E,(BC)", .arg_type = ARG_NONE},
	{.disp = "OUT  (BC),E", .arg_type = ARG_NONE},
	{.disp = "ADC  HL,DE", .arg_type = ARG_NONE},
	{.disp = "LD   DE,(%s)", .arg_type = ARG_WORD},
	{.disp = "MULT DE", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "IM   2", .arg_type = ARG_NONE},
	{.disp = "LD   A,R", .arg_type = ARG_NONE},
	{.disp = "IN   H,(BC)", .arg_type = ARG_NONE},
	{.disp = "OUT  (BC),H", .arg_type = ARG_NONE},
	{.disp = "SBC  HL,HL", .arg_type = ARG_NONE},
	{.disp = "LD   (%s),HL", .arg_type = ARG_WORD},
	{.disp = "TST  A,%s", .arg_type = ARG_BYTE},
	{.disp = "PEA  IX+%s", .arg_type = ARG_BYTE},
	{.disp = "PEA  IY+%s", .arg_type = ARG_BYTE},
	{.disp = "RRD", .arg_type = ARG_NONE},
	{.disp = "IN   L,(BC)", .arg_type = ARG_NONE},
	{.disp = "OUT  (BC),L", .arg_type = ARG_NONE},
	{.disp = "ADC  HL,HL", .arg_type = ARG_NONE},
	{.disp = "LD   HL,(%s)", .arg_type = ARG_WORD},
	{.disp = "MULT HL", .arg_type = ARG_NONE},
	{.disp = "LD   MB,A", .arg_type = ARG_NONE},
	{.disp = "LD   A,MB", .arg_type = ARG_NONE},
	{.disp = "RLD", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SBC  HL,SP", .arg_type = ARG_NONE},
	{.disp = "LD   (%s),SP", .arg_type = ARG_WORD},
	{.disp = "TSR  (%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SLP", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "IN   A,(BC)", .arg_type = ARG_NONE},
	{.disp = "OUT  (BC),A", .arg_type = ARG_NONE},
	{.disp = "ADC  HL,SP", .arg_type = ARG_NONE},
	{.disp = "LD   SP,(%s)", .arg_type = ARG_WORD},
	{.disp = "MULT SP", .arg_type = ARG_NONE},
	{.disp = "STMIX", .arg_type = ARG_NONE},
	{.disp = "RSMIX", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "INIM", .arg_type = ARG_NONE},
	{.disp = "OTIM", .arg_type = ARG_NONE},
	{.disp = "INI2", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "INDM", .arg_type = ARG_NONE},
	{.disp = "OTDM", .arg_type = ARG_NONE},
	{.disp = "IND2", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "INIMR", .arg_type = ARG_NONE},
	{.disp = "OTIMR", .arg_type = ARG_NONE},
	{.disp = "INI2R", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "INDMR", .arg_type = ARG_NONE},
	{.disp = "OTDMR", .arg_type = ARG_NONE},
	{.disp = "IND2R", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LDI", .arg_type = ARG_NONE},
	{.disp = "CPI", .arg_type = ARG_NONE},
	{.disp = "INI", .arg_type = ARG_NONE},
	{.disp = "OTI", .arg_type = ARG_NONE},
	{.disp = "OTI2", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LDD", .arg_type = ARG_NONE},
	{.disp = "CPD", .arg_type = ARG_NONE},
	{.disp = "IND", .arg_type = ARG_NONE},
	{.disp = "OTD", .arg_type = ARG_NONE},
	{.disp = "OTD2", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LDIR", .arg_type = ARG_NONE},
	{.disp = "CPIR", .arg_type = ARG_NONE},
	{.disp = "INIR", .arg_type = ARG_NONE},
	{.disp = "OTIR", .arg_type = ARG_NONE},
	{.disp = "ORI2R", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LDDR", .arg_type = ARG_NONE},
	{.disp = "CPDR", .arg_type = ARG_NONE},
	{.disp = "INDR", .arg_type = ARG_NONE},
	{.disp = "OTDR", .arg_type = ARG_NONE},
	{.disp = "OTD2R", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
};

opcode_t dd_table[256] = {
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   BC,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  IX,BC", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (IX+%s),BC", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   DE,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  IX,DE", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (IX+%s),DE", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   IX,%s", .arg_type = ARG_WORD},
	{.disp = "LD   (%s),IX", .arg_type = ARG_WORD},
	{.disp = "INC  IX", .arg_type = ARG_NONE},
	{.disp = "INC  IXH", .arg_type = ARG_NONE},
	{.disp = "DEC  IXH", .arg_type = ARG_NONE},
	{.disp = "LD   IXH,%s", .arg_type = ARG_BYTE},
	{.disp = "LD   HL,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  IX,IX", .arg_type = ARG_NONE},
	{.disp = "LD   IX,(%s)", .arg_type = ARG_WORD},
	{.disp = "DEC  IX", .arg_type = ARG_NONE},
	{.disp = "INC  IXL", .arg_type = ARG_NONE},
	{.disp = "DEC  IXL", .arg_type = ARG_NONE},
	{.disp = "LD   IXL,%s", .arg_type = ARG_BYTE},
	{.disp = "LD   (IX+%s),HL", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   IY,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "INC  (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = "DEC  (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = "LD   (IX+%s),%s", .arg_type = ARG_D_IMM},
	{.disp = "LD   IX,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  IX,SP", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (IX+%s),IY", .arg_type = ARG_BYTE},
	{.disp = "LD   (IX+%s),IX", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   B,IXH", .arg_type = ARG_NONE},
	{.disp = "LD   B,IXL", .arg_type = ARG_NONE},
	{.disp = "LD   B,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   C,IXH", .arg_type = ARG_NONE},
	{.disp = "LD   C,IXL", .arg_type = ARG_NONE},
	{.disp = "LD   C,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   D,IXH", .arg_type = ARG_NONE},
	{.disp = "LD   D,IXL", .arg_type = ARG_NONE},
	{.disp = "LD   D,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   E,IXH", .arg_type = ARG_NONE},
	{.disp = "LD   E,IXL", .arg_type = ARG_NONE},
	{.disp = "LD   E,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   IXH,B", .arg_type = ARG_NONE},
	{.disp = "LD   IXH,C", .arg_type = ARG_NONE},
	{.disp = "LD   IXH,D", .arg_type = ARG_NONE},
	{.disp = "LD   IXH,E", .arg_type = ARG_NONE},
	{.disp = "LD   IXH,IXH", .arg_type = ARG_NONE},
	{.disp = "LD   IXH,IXL", .arg_type = ARG_NONE},
	{.disp = "LD   H,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = "LD   IXH,A", .arg_type = ARG_NONE},
	{.disp = "LD   IXL,B", .arg_type = ARG_NONE},
	{.disp = "LD   IXL,C", .arg_type = ARG_NONE},
	{.disp = "LD   IXL,D", .arg_type = ARG_NONE},
	{.disp = "LD   IXL,E", .arg_type = ARG_NONE},
	{.disp = "LD   IXL,IXH", .arg_type = ARG_NONE},
	{.disp = "LD   IXL,IXL", .arg_type = ARG_NONE},
	{.disp = "LD   L,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = "LD   IXL,A", .arg_type = ARG_NONE},
	{.disp = "LD   (IX+%s),B", .arg_type = ARG_BYTE},
	{.disp = "LD   (IX+%s),C", .arg_type = ARG_BYTE},
	{.disp = "LD   (IX+%s),D", .arg_type = ARG_BYTE},
	{.disp = "LD   (IX+%s),E", .arg_type = ARG_BYTE},
	{.disp = "LD   (IX+%s),H", .arg_type = ARG_BYTE},
	{.disp = "LD   (IX+%s),L", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (IX+%s),A", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   A,IXH", .arg_type = ARG_NONE},
	{.disp = "LD   A,IXL", .arg_type = ARG_NONE},
	{.disp = "LD   A,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  A,IXH", .arg_type = ARG_NONE},
	{.disp = "ADD  A,IXL", .arg_type = ARG_NONE},
	{.disp = "ADD  A,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADC  A,IXH", .arg_type = ARG_NONE},
	{.disp = "ADC  A,IXL", .arg_type = ARG_NONE},
	{.disp = "ADC  A,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SUB  A,IXH", .arg_type = ARG_NONE},
	{.disp = "SUB  A,IXL", .arg_type = ARG_NONE},
	{.disp = "SUB  A,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SBC  A,IXH", .arg_type = ARG_NONE},
	{.disp = "SBC  A,IXL", .arg_type = ARG_NONE},
	{.disp = "SBC  A,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "AND  IXH", .arg_type = ARG_NONE},
	{.disp = "AND  IXL", .arg_type = ARG_NONE},
	{.disp = "AND  (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "XOR  IXH", .arg_type = ARG_NONE},
	{.disp = "XOR  IXL", .arg_type = ARG_NONE},
	{.disp = "XOR  (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "OR   IXH", .arg_type = ARG_NONE},
	{.disp = "OR   IXL", .arg_type = ARG_NONE},
	{.disp = "OR   (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "CP   IXH", .arg_type = ARG_NONE},
	{.disp = "CP   IXL", .arg_type = ARG_NONE},
	{.disp = "CP   (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "POP  IX", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "EX   (SP),IX", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "PUSH IX", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "JP   (IX)", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   SP,IX", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
};

opcode_t fd_cb_table[256] = {
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RLC (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RRC (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RL  (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RR  (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SLA (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SRA (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SRL (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 0,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 1,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 2,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 3,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 4,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 5,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 6,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 7,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 0,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 1,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 2,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 3,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 4,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 5,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 6,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 7,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 0,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 1,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 2,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 3,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 4,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 5,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 6,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 7,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
};

opcode_t dd_cb_table[256] = {
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RLC (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RRC (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RL  (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RR  (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SLA (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SRA (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SRL (IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 0,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 1,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 2,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 3,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 4,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 5,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 6,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "BIT 7,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 0,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 1,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 2,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 3,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 4,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 5,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 6,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "RES 7,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 0,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 1,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 2,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 3,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 4,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 5,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 6,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SET 7,(IX+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
};

opcode_t fd_table[256] = {
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   BC,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  IY,BC", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (IY+%s),BC", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   DE,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  IY,DE", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (IY+%s),DE", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   IY,%s", .arg_type = ARG_WORD},
	{.disp = "LD   (%s),IY", .arg_type = ARG_WORD},
	{.disp = "INC  IY", .arg_type = ARG_NONE},
	{.disp = "INC  IYH", .arg_type = ARG_NONE},
	{.disp = "DEC  IYH", .arg_type = ARG_NONE},
	{.disp = "LD   IYH,%s", .arg_type = ARG_BYTE},
	{.disp = "LD   HL,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  IY,IY", .arg_type = ARG_NONE},
	{.disp = "LD   IY,(%s)", .arg_type = ARG_WORD},
	{.disp = "DEC  IY", .arg_type = ARG_NONE},
	{.disp = "INC  IYL", .arg_type = ARG_NONE},
	{.disp = "DEC  IYL", .arg_type = ARG_NONE},
	{.disp = "LD   IYL,%s", .arg_type = ARG_BYTE},
	{.disp = "LD   (IY+%s),HL", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   IY,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "INC  (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = "DEC  (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = "LD   (IY+%s),%s", .arg_type = ARG_D_IMM},
	{.disp = "LD   IY,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  IY,SP", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (IY+%s),IY", .arg_type = ARG_BYTE},
	{.disp = "LD   (IY+%s),IY", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   B,IYH", .arg_type = ARG_NONE},
	{.disp = "LD   B,IYL", .arg_type = ARG_NONE},
	{.disp = "LD   B,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   C,IYH", .arg_type = ARG_NONE},
	{.disp = "LD   C,IYL", .arg_type = ARG_NONE},
	{.disp = "LD   C,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   D,IYH", .arg_type = ARG_NONE},
	{.disp = "LD   D,IYL", .arg_type = ARG_NONE},
	{.disp = "LD   D,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   E,IYH", .arg_type = ARG_NONE},
	{.disp = "LD   E,IYL", .arg_type = ARG_NONE},
	{.disp = "LD   E,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   IYH,B", .arg_type = ARG_NONE},
	{.disp = "LD   IYH,C", .arg_type = ARG_NONE},
	{.disp = "LD   IYH,D", .arg_type = ARG_NONE},
	{.disp = "LD   IYH,E", .arg_type = ARG_NONE},
	{.disp = "LD   IYH,IYH", .arg_type = ARG_NONE},
	{.disp = "LD   IYH,IYL", .arg_type = ARG_NONE},
	{.disp = "LD   H,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = "LD   IYH,A", .arg_type = ARG_NONE},
	{.disp = "LD   IYL,B", .arg_type = ARG_NONE},
	{.disp = "LD   IYL,C", .arg_type = ARG_NONE},
	{.disp = "LD   IYL,D", .arg_type = ARG_NONE},
	{.disp = "LD   IYL,E", .arg_type = ARG_NONE},
	{.disp = "LD   IYL,IYH", .arg_type = ARG_NONE},
	{.disp = "LD   IYL,IYL", .arg_type = ARG_NONE},
	{.disp = "LD   L,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = "LD   IYL,A", .arg_type = ARG_NONE},
	{.disp = "LD   (IY+%s),B", .arg_type = ARG_BYTE},
	{.disp = "LD   (IY+%s),C", .arg_type = ARG_BYTE},
	{.disp = "LD   (IY+%s),D", .arg_type = ARG_BYTE},
	{.disp = "LD   (IY+%s),E", .arg_type = ARG_BYTE},
	{.disp = "LD   (IY+%s),H", .arg_type = ARG_BYTE},
	{.disp = "LD   (IY+%s),L", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   (IY+%s),A", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   A,IYH", .arg_type = ARG_NONE},
	{.disp = "LD   A,IYL", .arg_type = ARG_NONE},
	{.disp = "LD   A,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADD  A,IYH", .arg_type = ARG_NONE},
	{.disp = "ADD  A,IYL", .arg_type = ARG_NONE},
	{.disp = "ADD  A,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "ADC  A,IYH", .arg_type = ARG_NONE},
	{.disp = "ADC  A,IYL", .arg_type = ARG_NONE},
	{.disp = "ADC  A,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SUB  A,IYH", .arg_type = ARG_NONE},
	{.disp = "SUB  A,IYL", .arg_type = ARG_NONE},
	{.disp = "SUB  A,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "SBC  A,IYH", .arg_type = ARG_NONE},
	{.disp = "SBC  A,IYL", .arg_type = ARG_NONE},
	{.disp = "SBC  A,(IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "AND  IYH", .arg_type = ARG_NONE},
	{.disp = "AND  IYL", .arg_type = ARG_NONE},
	{.disp = "AND  (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "XOR  IYH", .arg_type = ARG_NONE},
	{.disp = "XOR  IYL", .arg_type = ARG_NONE},
	{.disp = "XOR  (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "OR   IYH", .arg_type = ARG_NONE},
	{.disp = "OR   IYL", .arg_type = ARG_NONE},
	{.disp = "OR   (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "CP   IYH", .arg_type = ARG_NONE},
	{.disp = "CP   IYL", .arg_type = ARG_NONE},
	{.disp = "CP   (IY+%s)", .arg_type = ARG_BYTE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "POP  IY", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "EX   (SP),IY", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "PUSH IY", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "JP   (IY)", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = "LD   SP,IY", .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
	{.disp = NULL, .arg_type = ARG_NONE},
};
